# Generated by Django 5.1.5 on 2026-02-16 18:31

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='analyzejob',
            name='source_input',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='analyzejob',
            name='source_type',
            field=models.CharField(choices=[('cv', 'CV'), ('github', 'GitHub')], default='cv', max_length=20),
        ),
        migrations.AlterField(
            model_name='analyzejob',
            name='source_file_key',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AddIndex(
            model_name='analyzejob',
            index=models.Index(fields=['source_type', 'created_at'], name='analysis_an_source__2bfe48_idx'),
        ),
    ]
